name: "Setup node"

description: "Setup node and cache ~/.npm"

runs:
  using: "composite"
  steps:
    - id: get-version
      shell: bash
      run: |
        nodejs=$(cat .tool-versions | grep nodejs | awk '{ print $2 }')
        echo "::set-output name=nodejs::${nodejs}"

    # https://github.com/actions/setup-node
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.get-version.outputs.nodejs }}
        cache: "npm"

    # https://github.com/actions/cache
    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: ${{ runner.os }}-npm-
